import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { chromium } from '../adapters/visual/node_modules/playwright-core/index.mjs';
const base=(process.env.GARY_UI_BASE_URL || 'http://127.0.0.1:4191').replace(/\/$/, '');
const reportPath=path.join(process.env.GARY_UI_CAPTURE_DIR || fs.mkdtempSync(path.join(os.tmpdir(), 'gary-pointer-')), 'pointer-effects.json');
fs.mkdirSync(path.dirname(reportPath), {recursive:true});
const browser=await chromium.launch({executablePath:process.env.GARY_UI_CHROME || chromium.executablePath(),headless:true});
const checks=[],errors=[];
const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
const frame=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const pixels=page=>page.locator('.gary-dot-grid-canvas').evaluate(el=>el.toDataURL());
const effects=page=>page.locator('#card').evaluate(el=>({x:el.style.getPropertyValue('--gary-card-x'),y:el.style.getPropertyValue('--gary-card-y'),light:getComputedStyle(el,'::before').opacity,orbit:getComputedStyle(el,'::after').animationName,focus:getComputedStyle(el).outlineStyle}));
async function fixture(withPanel){
  const page=await browser.newPage({viewport:{width:1100,height:800}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{
    window.waveTranslations=[];
    const original=CanvasRenderingContext2D.prototype.translate;
    CanvasRenderingContext2D.prototype.translate=function(x,y){
      if(this.canvas.classList.contains('gary-gradient-waves-canvas')&&x>0&&y>0)window.waveTranslations.push([x,y]);
      return original.call(this,x,y);
    };
  });
  await page.route('**/__pointerfixture.html',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html data-gary-theme="dark"><head><link rel="stylesheet" href="/tokens/base.css"><link rel="stylesheet" href="/patterns/shared/background-lab.css"><style>body{margin:0;--demo-bg:#000;--demo-panel:#101012;--demo-ink:#eee;--demo-muted:#aaa;--demo-line:#333}#scene{position:fixed;inset:0;width:1100px;height:800px;z-index:-1;pointer-events:none}#card,#optical{position:absolute;top:100px;left:40px;width:260px;height:160px;padding:28px}#optical{left:340px}button{min-width:44px;min-height:44px}</style></head><body><div id="scene" class="gary-scene" data-gary-background-host data-gary-scene-engine="dot-grid"></div><button data-background-open>Background</button><a id="card" href="#clicked" data-gary-material="glass">查看数据</a><a id="optical" href="#optical" data-gary-material="glass" data-gary-refraction>光学卡片</a><script src="/patterns/shared/dot-grid.js"></script><script src="/patterns/shared/material.js"></script><script src="/patterns/shared/optical-glass.js"></script><script src="/patterns/shared/ambient-waves.js"></script>${withPanel?'<script src="/patterns/shared/background-lab.js"></script>':''}</body></html>`}));
  await page.goto(base+'/__pointerfixture.html',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>document.querySelector('#scene').dataset.sceneStatus==='ready');
  return page;
}
try{
 const page=await fixture(false);
 const baseline=await pixels(page);
 await page.mouse.move(140,165);await frame(page);
 check('No panel: missing root attribute keeps dot pixels unchanged',await pixels(page)===baseline);
 let state=await effects(page);check('No panel: missing root attribute blocks card light and coordinate writes',!state.x&&state.light==='0'&&state.orbit==='none');
 await page.evaluate(()=>document.documentElement.dataset.garyPointerEffects='on');await frame(page);await page.mouse.move(150,175);await page.waitForTimeout(250);
 check('Attribute opt-in changes actual dot pixels',await pixels(page)!==baseline);
 state=await effects(page);check('Attribute opt-in enables card light',!!state.x&&state.light==='1'&&state.orbit==='gary-card-orbit');
 await page.mouse.move(430,165);await page.waitForTimeout(250);
 check('Optical card never adds edge orbit',await page.locator('#optical').evaluate(el=>el.dataset.garyRefractionState==='svg'&&getComputedStyle(el,'::after').animationName==='none'));
 await page.mouse.move(155,180);await frame(page);
 await page.evaluate(()=>document.documentElement.dataset.garyPointerEffects='off');await frame(page);
 check('Attribute off resets dots exactly without residual displacement',await pixels(page)===baseline);
 state=await effects(page);check('Attribute off clears card coordinates and light immediately',!state.x&&!state.y&&state.light==='0'&&state.orbit==='none');
 await page.locator('#card').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');
 check('Keyboard focus remains visible when effects are off',await page.locator('#card').evaluate(el=>el.matches(':focus-visible')&&getComputedStyle(el).outlineStyle!=='none'));
 await page.keyboard.press('Enter');check('Card click remains functional',page.url().endsWith('#clicked'));
 await page.evaluate(()=>{document.activeElement.blur();document.documentElement.dataset.garyPointerEffects='on';document.querySelector('#scene').dataset.motionOverride='on';});
 await page.mouse.move(160,185);await frame(page);await page.emulateMedia({reducedMotion:'reduce'});await frame(page);
 check('Reduced motion resets dots even with old scene override on',await pixels(page)===baseline);
 state=await effects(page);check('Reduced motion clears coordinates and hover light',!state.x&&state.light==='0'&&state.orbit==='none');
 await page.emulateMedia({reducedMotion:'no-preference'});await frame(page);
 check('Re-enable retains static dots until next pointer move',await pixels(page)===baseline);
 await page.evaluate(()=>{document.documentElement.removeAttribute('data-gary-pointer-effects');window.wave=GaryGradientWaves.mount(document.querySelector('#scene'));window.waveTranslations=[];});
 check('Standalone waves API default mouseInteraction is false',await page.evaluate(()=>!GaryGradientWaves.defaults.mouseInteraction&&!wave.state.options.mouseInteraction));
 await page.mouse.move(1000,650);await page.waitForTimeout(180);
 check('Standalone default waves remain centered on pointer movement',await page.evaluate(()=>waveTranslations.length>0&&waveTranslations.every(([x,y])=>x===550&&y===400)));
 await page.evaluate(()=>{wave.update({mouseInteraction:true});window.waveTranslations=[];});await page.mouse.move(900,600);await page.waitForTimeout(180);
 check('Standalone explicit local mouse setting cannot bypass root off',await page.evaluate(()=>waveTranslations.length>0&&waveTranslations.every(([x,y])=>x===550&&y===400)));
 await page.evaluate(()=>{document.documentElement.dataset.garyPointerEffects='on';window.waveTranslations=[];});await frame(page);await page.mouse.move(950,620);await page.waitForTimeout(300);
 check('Standalone waves parallax works after root opt-in',await page.evaluate(()=>waveTranslations.some(([x,y])=>Math.abs(x-550)>.1||Math.abs(y-400)>.1)));
 await page.evaluate(()=>{document.documentElement.dataset.garyPointerEffects='off';window.waveTranslations=[];});await frame(page);
 check('Standalone waves root off immediately recenters',await page.evaluate(()=>waveTranslations.length>0&&waveTranslations.every(([x,y])=>x===550&&y===400)));
 await page.evaluate(()=>{wave.pause();document.documentElement.dataset.garyPointerEffects='on';});await frame(page);
 check('Root changes preserve wave pause',await page.evaluate(()=>wave.state.status==='paused'));
 await page.close();
 const panelPage=await fixture(true);
 await panelPage.locator('[data-background-open]').click();
 check('Background checkbox defaults unchecked',!await panelPage.locator('[name="pointerEffects"]').isChecked());
 check('No independent local mouse checkbox can contradict total setting',await panelPage.locator('[name="mouseInteraction"]').count()===0);
 await panelPage.evaluate(()=>{window.pointerEvents=[];addEventListener('gary:pointer-effects-change',e=>pointerEvents.push(e.detail.enabled));});
 await panelPage.locator('[name="background"]').selectOption('gradient-waves');
 await panelPage.waitForFunction(()=>GaryBackgroundLab.engine?.state.status==='playing');
 check('Background wave selection preserves autoplay but pointer off',await panelPage.evaluate(()=>GaryBackgroundLab.engine.state.status==='playing'&&!GaryBackgroundLab.engine.state.options.mouseInteraction));
 await panelPage.locator('[name="pointerEffects"]').check();
 check('Background checkbox enables root and wave option',await panelPage.evaluate(()=>document.documentElement.dataset.garyPointerEffects==='on'&&GaryBackgroundLab.engine.state.options.mouseInteraction&&pointerEvents.at(-1)===true));
 await panelPage.locator('[name="preset"]').selectOption('original');
 await panelPage.locator('[name="pointerEffects"]').uncheck();
 check('Background checkbox disables root and even original recipe wave pointer',await panelPage.evaluate(()=>document.documentElement.dataset.garyPointerEffects==='off'&&!GaryBackgroundLab.engine.state.options.mouseInteraction&&pointerEvents.at(-1)===false));
 await panelPage.locator('[data-waves-reset]').click();
 check('Recipe reset does not re-enable pointer',await panelPage.evaluate(()=>!GaryBackgroundLab.engine.state.options.mouseInteraction));
 await panelPage.locator('[data-background-close]').click();
 await panelPage.evaluate(()=>document.documentElement.dataset.garyPointerEffects='on');await frame(panelPage);
 await panelPage.locator('[data-background-open]').click();
 check('Reopened panel reflects root state',await panelPage.locator('[name="pointerEffects"]').isChecked());
 await panelPage.reload({waitUntil:'networkidle'});await panelPage.locator('[data-background-open]').click();
 check('Reload never restores pointer opt-in',!await panelPage.locator('[name="pointerEffects"]').isChecked());
 check('No browser errors',errors.length===0);
 fs.writeFileSync(reportPath,JSON.stringify({status:'pass',checkedAt:new Date().toISOString(),checks,errors},null,2));
 console.log(JSON.stringify({status:'pass',checks:checks.length,report:reportPath}));
}finally{await browser.close();}
