/*
 * prebuild: inline the Gary-UI token cascade into a self-contained
 * dist/styles/gary-ui.css.
 *
 * Consumers import "@gary-ui/react-shadcn/styles.css" from node_modules, where
 * the source-repo-relative `@import "../../../../tokens/base.css"` cannot
 * resolve and breaks the consumer build. This script resolves that @import
 * chain (tokens/base.css -> components/components.css) at build time and
 * rewrites relative url() references so the emitted file is self-contained.
 * The source src/styles/gary-ui.css keeps its @import for development.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { posix } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ADAPTER_ROOT = resolve(SCRIPT_DIR, "..");
const REPO_ROOT = resolve(ADAPTER_ROOT, "..", "..");

const BASE_CSS = join(REPO_ROOT, "tokens", "base.css");
const ADAPTER_CSS = join(ADAPTER_ROOT, "src", "styles", "gary-ui.css");
const OUT_FILE = join(ADAPTER_ROOT, "dist", "styles", "gary-ui.css");

const IMPORT_RE = /^\s*@import\s+(?:url\(\s*)?(["']?)([^"')]+)\1\s*\)?\s*;\s*$/m;
const URL_RE = /url\((["']?)([^"')]+)\1\)/g;
const EXTERNAL_RE = /^(?:data:|https?:|\/)/i;

function read(path) {
  return readFileSync(path, "utf8");
}

/** 递归解析 @import url(...)（仅相对路径），返回拼接后的 CSS。 */
function resolveImports(entryPath, seen = new Set()) {
  const abs = resolve(entryPath);
  if (seen.has(abs)) {
    throw new Error(`circular @import detected at ${abs}`);
  }
  seen.add(abs);
  let css = read(abs);
  let match;
  while ((match = css.match(IMPORT_RE)) !== null) {
    const [, quote, target] = match;
    if (EXTERNAL_RE.test(target)) {
      throw new Error(`unsupported @import target in ${abs}: ${target}`);
    }
    css = css.replace(match[0], resolveImports(resolve(dirname(abs), target), seen));
  }
  return css;
}

/** 把 url() 相对引用改写为相对输出文件（dist/styles/）的路径。 */
function rewriteUrls(css, fromFile) {
  const outDir = dirname(OUT_FILE).split(/[\\/]/).join("/");
  return css.replace(URL_RE, (full, quote, target) => {
    if (EXTERNAL_RE.test(target)) return full;
    const absolute = resolve(dirname(fromFile), target).split(/[\\/]/).join("/");
    return `url(${quote}${posix.relative(outDir, absolute)}${quote})`;
  });
}

function main() {
  const baseCss = resolveImports(BASE_CSS);
  const baseCssResolved = rewriteUrls(baseCss, BASE_CSS);

  // 源码保留 @import 供开发；发布产物中移除，避免 node_modules 下路径失效。
  const adapterCss = read(ADAPTER_CSS).replace(IMPORT_RE, "");

  const banner = `/*
 * Gary-UI React/shadcn adapter styles — self-contained build artifact.
 * Generated by scripts/inline-styles.mjs (prebuild); do not edit by hand.
 * Values remain authoritative in ../../../../tokens/tokens.json.
 */

`;

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, banner + baseCssResolved + "\n\n" + adapterCss, "utf8");
  console.log(`inline-styles: wrote ${OUT_FILE}`);
}

main();
